"""
The beginner's layer-by-layer method, as a solver.

This is deliberately not a good solver. A good solver (Kociemba, Thistlethwaite)
finds a twenty-move solution that no human could reconstruct, and the video is
about the opposite claim: that a handful of short sequences, each of which puts
back everything it disturbs, is enough to solve anything. So the search here is
over *those sequences* and nothing else, and its output is the video's script.

Each stage searches breadth-first over an alphabet of whole algorithms plus U
turns, with a goal that includes "everything solved so far is still solved".
The alphabets are small and the goals are shallow, so every stage completes in
milliseconds -- and because the alphabet is the method's own move set, the
solution it prints is one a person could have found.

The one exception is the white cross, where the alphabet is the eighteen face
turns: the cross is the only part with no algorithm, and beginners really do
find it by looking.

    python solver.py                 # solve a fixed scramble, print the stages
    python solver.py --seed 12       # a different one
    python solver.py --test          # solve 300 random scrambles
"""

from collections import deque

from cube_model import (
    SOLVED, SLOT_INDEX, IDENT, FACE_MOVES, apply, apply_one, parse, fmt,
    scramble, simplify, laws,
)

# ── the slots each stage is responsible for ──────────────────────────────

CROSS = [(0, -1, 1), (1, -1, 0), (0, -1, -1), (-1, -1, 0)]      # DF DR DB DL
FIRST_CORNERS = [(1, -1, 1), (1, -1, -1), (-1, -1, -1), (-1, -1, 1)]
MIDDLE = [(1, 0, 1), (1, 0, -1), (-1, 0, -1), (-1, 0, 1)]       # FR RB BL LF
LL_EDGES = [(0, 1, 1), (1, 1, 0), (0, 1, -1), (-1, 1, 0)]
LL_CORNERS = [(1, 1, 1), (1, 1, -1), (-1, 1, -1), (-1, 1, 1)]

# ── the method's algorithms ──────────────────────────────────────────────
#
# Each slot's version is the same physical sequence seen from a different
# side, so they are generated by walking the faces round rather than written
# out four times: F -> R -> B -> L is one quarter turn of the whole cube.

_RING = ["F", "R", "B", "L"]


def _turned(alg, steps):
    """The same algorithm, performed a quarter turn round the cube."""
    shift = {f: _RING[(i + steps) % 4] for i, f in enumerate(_RING)}
    return [shift.get(m[0], m[0]) + m[1:] for m in parse(alg)]


#: (front face, right face) of each first-layer slot, in _RING order.
SLOT_FACES = [("F", "R"), ("R", "B"), ("B", "L"), ("L", "F")]
#: The corner and middle edge each slot owns, indexed the same way.
SLOT_CORNER = [(1, -1, 1), (1, -1, -1), (-1, -1, -1), (-1, -1, 1)]
SLOT_EDGE = [(1, 0, 1), (1, 0, -1), (-1, 0, -1), (-1, 0, 1)]

# "the trigger": take the corner out, turn the top, put it back. Six of these
# return the cube to where it started, which is the video's central claim.
TRIGGER = "R U R' U'"
# insert a middle edge from the top layer, to the right and to the left
INSERT_RIGHT = "U R U' R' U' F' U F"
INSERT_LEFT = "U' F' U F U R U' R'"
# last layer
OLL_EDGES = "F R U R' U' F'"            # dot -> line -> L -> cross
SUNE = "R U R' U R U2 R'"               # twist three corners
A_PERM = "R' F R' B2 R F' R' B2 R2"     # cycle three corners
U_PERM = "R U' R U R U R U' R' U' R2"   # cycle three edges
U_PERM_INV = "R2 U R U R' U' R' U' R' U R'"

U_TURNS = [("U", ["U"]), ("U2", ["U2"]), ("U'", ["U'"])]
TRIGGERS = [(f"trigger@{SLOT_FACES[i][0]}{SLOT_FACES[i][1]}",
             _turned(TRIGGER, i)) for i in range(4)]
INSERTS = ([(f"insert-R@{SLOT_FACES[i][0]}{SLOT_FACES[i][1]}",
             _turned(INSERT_RIGHT, i)) for i in range(4)]
           + [(f"insert-L@{SLOT_FACES[i][0]}{SLOT_FACES[i][1]}",
               _turned(INSERT_LEFT, i)) for i in range(4)])


# ── search ───────────────────────────────────────────────────────────────

def solved_at(state, slots):
    """Every piece in `slots` is home and the right way up.

    A slot holds the identity rotation exactly when the piece in it is its own
    piece, correctly oriented -- that is the whole "is it solved" test, and it
    is why the model is 26 rotations rather than four permutation arrays.
    """
    return all(state[SLOT_INDEX[s]] == IDENT for s in slots)


def bfs(state, alphabet, goal, max_depth):
    """Shortest sequence of whole algorithms reaching `goal`, or None."""
    if goal(state):
        return []
    seen = {state}
    queue = deque([(state, [])])
    while queue:
        st, path = queue.popleft()
        if len(path) >= max_depth:
            continue
        for name, moves in alphabet:
            nxt = apply(st, moves)
            if nxt in seen:
                continue
            if goal(nxt):
                return path + [(name, moves)]
            seen.add(nxt)
            queue.append((nxt, path + [(name, moves)]))
    return None


_AXIS = {"U": 0, "D": 0, "R": 1, "L": 1, "F": 2, "B": 2}


def ida(state, goal, max_depth):
    """Iterative deepening over single face turns. Used only for the cross.

    Two prunings keep the branching factor near thirteen instead of eighteen:
    never turn the same face twice in a row, and when two opposite faces are
    turned in succession, allow only one of the two orders (they commute, so
    the other order is the same sequence twice).
    """
    def dfs(st, depth, path):
        if goal(st):
            return path
        if depth == 0:
            return None
        for m in FACE_MOVES:
            if path:
                prev = path[-1]
                if m[0] == prev[0]:
                    continue
                if (_AXIS[m[0]] == _AXIS[prev[0]] and m[0] > prev[0]):
                    continue
            found = dfs(apply_one(st, m), depth - 1, path + [m])
            if found is not None:
                return found
        return None

    for depth in range(max_depth + 1):
        found = dfs(state, depth, [])
        if found is not None:
            return found
    return None


class Unsolvable(Exception):
    pass


# ── the stages ───────────────────────────────────────────────────────────

def _cross(state):
    """The white cross: four edges, found by looking rather than by algorithm.

    Solved one edge at a time, and each search is told to keep the ones
    already placed. Which edge to do next is chosen by trying them all and
    taking the cheapest, because a fixed order occasionally forces a long
    detour that a person would simply have avoided.
    """
    moves, placed = [], []
    for _ in range(4):
        best = None
        for slot in CROSS:
            if slot in placed:
                continue
            keep = placed + [slot]
            found = ida(state, lambda s, k=keep: solved_at(s, k), 6)
            if found is not None and (best is None or len(found) < len(best[1])):
                best = (slot, found)
        if best is None:
            raise Unsolvable("white cross")
        slot, found = best
        state = apply(state, found)
        moves += found
        placed.append(slot)
    return state, moves


def _first_layer(state):
    """The four white corners, one trigger at a time."""
    moves, done = [], list(CROSS)
    alphabet = U_TURNS + TRIGGERS
    for corner in FIRST_CORNERS:
        keep = done + [corner]
        found = bfs(state, alphabet, lambda s, k=keep: solved_at(s, k), 8)
        if found is None:
            raise Unsolvable(f"first-layer corner {corner}")
        for _, mv in found:
            state = apply(state, mv)
            moves += mv
        done.append(corner)
    return state, moves


def _middle_layer(state):
    moves, done = [], CROSS + FIRST_CORNERS
    alphabet = U_TURNS + INSERTS
    for edge in MIDDLE:
        keep = done + [edge]
        found = bfs(state, alphabet, lambda s, k=keep: solved_at(s, k), 5)
        if found is None:
            raise Unsolvable(f"middle-layer edge {edge}")
        for _, mv in found:
            state = apply(state, mv)
            moves += mv
        done.append(edge)
    return state, moves


def _yellow_cross(state):
    """Orient the last four edges. Nothing is put in place yet, only turned up."""
    def goal(s):
        return all(_faces_up(s, slot) for slot in LL_EDGES)
    found = bfs(state, U_TURNS + [("OLL-edges", parse(OLL_EDGES))], goal, 6)
    if found is None:
        raise Unsolvable("yellow cross")
    return _run(state, found)


def _yellow_face(state):
    def goal(s):
        return all(_faces_up(s, slot) for slot in LL_CORNERS + LL_EDGES)
    found = bfs(state, U_TURNS + [("sune", parse(SUNE))], goal, 9)
    if found is None:
        raise Unsolvable("yellow face")
    return _run(state, found)


def _place_corners(state):
    found = bfs(state, U_TURNS + [("A-perm", parse(A_PERM))],
                lambda s: solved_at(s, LL_CORNERS), 9)
    if found is None:
        raise Unsolvable("last-layer corners")
    return _run(state, found)


def _place_edges(state):
    alphabet = U_TURNS + [("U-perm", parse(U_PERM)),
                          ("U-perm'", parse(U_PERM_INV))]
    found = bfs(state, alphabet, lambda s: s == SOLVED, 9)
    if found is None:
        raise Unsolvable("last-layer edges")
    return _run(state, found)


def _faces_up(state, slot):
    """The yellow sticker of the piece in `slot` points at the sky."""
    from cube_model import color_at, UP, FACE_COLOUR
    return color_at(state, slot, UP) == FACE_COLOUR["U"]


def _run(state, found):
    moves = []
    for _, mv in found:
        state = apply(state, mv)
        moves += mv
    return state, moves


STAGES = [
    ("cross", "the white cross", _cross),
    ("corners", "the four white corners", _first_layer),
    ("middle", "the middle layer", _middle_layer),
    ("yellow-cross", "the yellow cross", _yellow_cross),
    ("yellow-face", "the whole yellow face", _yellow_face),
    ("place-corners", "the last four corners, into place", _place_corners),
    ("place-edges", "the last four edges, into place", _place_edges),
]


def solve(state):
    """[(stage_key, description, [moves])], leaving the cube solved."""
    out = []
    for key, desc, fn in STAGES:
        before = state
        state, moves = fn(state)
        # Cancel the seams between stitched-together algorithms, then confirm
        # the shortened sequence still lands on exactly the same cube. A
        # simplifier that quietly changes the state would be invisible until
        # the last stage failed for no apparent reason.
        moves = simplify(moves)
        if apply(before, moves) != state:
            raise Unsolvable(f"simplifying {key} changed the cube")
        out.append((key, desc, moves))
    if state != SOLVED:
        raise Unsolvable("finished the method without a solved cube")
    return out


# ── entry point ──────────────────────────────────────────────────────────

def main(argv=None):
    import argparse
    import time
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=None)
    ap.add_argument("--moves", type=int, default=20)
    ap.add_argument("--scramble", help="use this scramble instead of a random one")
    ap.add_argument("--test", action="store_true",
                    help="solve 300 random scrambles and check every one")
    args = ap.parse_args(argv)

    if args.test:
        worst, t0 = 0, time.time()
        for seed in range(300):
            st = apply(SOLVED, scramble(25, seed=seed))
            stages = solve(st)
            n = sum(len(m) for _, _, m in stages)
            worst = max(worst, n)
            end = apply(st, [m for _, _, mv in stages for m in mv])
            assert end == SOLVED, f"seed {seed} did not solve"
            assert laws(end) == [], f"seed {seed} produced an illegal state"
        print(f"300/300 solved, longest {worst} moves, "
              f"{time.time() - t0:.1f}s")
        return 0

    scr = parse(args.scramble) if args.scramble else scramble(args.moves,
                                                              seed=args.seed)
    state = apply(SOLVED, scr)
    print(f"scramble  {fmt(scr)}\n")
    total = 0
    for key, desc, moves in solve(state):
        state = apply(state, moves)
        total += len(moves)
        print(f"{key:<14} {len(moves):3d}  {fmt(moves)}")
    print(f"\n{total} moves, solved: {state == SOLVED}")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
